import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReportPDF = ({
  quotations = [],
  customers = [],
  furniture = [],
  totalRevenue = 0,
}) => {
  const pdf = new jsPDF();

  // ==========================================
  // HEADER
  // ==========================================

  pdf.setFontSize(20);
  pdf.setTextColor(44, 62, 80);

  pdf.text(
    "SHARMA INTERIORS & FURNITURE",
    14,
    20
  );

  pdf.setFontSize(9);

  pdf.text(
    "Interior Design | Modular Furniture | Custom Woodwork",
    14,
    27
  );

  pdf.text(
    "Phone : 9960040174",
    14,
    34
  );

  pdf.text(
    "Email : ayodhyasharma06@gmail.com",
    14,
    40
  );

  pdf.setFillColor(75, 55, 120);

  pdf.rect(
    145,
    15,
    50,
    10,
    "F"
  );

  pdf.setTextColor(255);

  pdf.setFontSize(12);

  pdf.text(
    "REPORT",
    159,
    22
  );

  pdf.setTextColor(0);

  pdf.setFontSize(10);

  pdf.text(
    `Generated : ${new Date().toLocaleDateString()}`,
    145,
    35
  );

  // ==========================================
  // BUSINESS SUMMARY
  // ==========================================

  autoTable(pdf, {
    startY: 50,

    head: [["Business Summary", "Value"]],

    body: [
      [
        "Total Revenue",
        `Rs. ${Number(totalRevenue).toLocaleString(
          "en-IN",
          {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }
        )}`,
      ],

      [
        "Total Quotations",
        quotations.length,
      ],

      [
        "Total Customers",
        customers.length,
      ],

      [
        "Furniture Items",
        furniture.length,
      ],
    ],

    theme: "grid",

    headStyles: {
      fillColor: [75, 55, 120],
      textColor: 255,
    },

    styles: {
      fontSize: 10,
    },
  });

  // ==========================================
  // RECENT QUOTATIONS
  // ==========================================

  const rows = quotations
    .slice()
    .reverse()
    .slice(0, 10)
    .map((q) => [
      q.invoiceNo,
      q.customerName,
      q.phone,
      q.date,
      `Rs. ${Number(
        q.grandTotal
      ).toLocaleString("en-IN", {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })}`,
    ]);

  autoTable(pdf, {
    startY:
      (pdf.lastAutoTable?.finalY || 60) + 12,

    head: [
      [
        "Invoice",
        "Customer",
        "Phone",
        "Date",
        "Amount",
      ],
    ],

    body: rows,

    theme: "striped",

    headStyles: {
      fillColor: [75, 55, 120],
      textColor: 255,
    },

    styles: {
      fontSize: 9,
    },

    columnStyles: {
      4: {
        halign: "right",
      },
    },
  });

  // ==========================================
  // FOOTER
  // ==========================================

  pdf.setFontSize(10);

  pdf.setTextColor(100);

  pdf.text(
    "Generated by CarpenterPro",
    72,
    285
  );

  pdf.save(
    `Business_Report_${Date.now()}.pdf`
  );
};